export const falcoeiros = [
  'Amilcar Fernandes',
  'Claudio Rodrigues',
  'David Silva',
  'Eduardo Esteves',
  'Filipe Coelho',
  'Flavia Carneiro',
  'Francisco Caramelo',
  'Guilherme',
  'Joana Silva',
  'João Francisco Silva',
  'João Vitor Sousa',
  'Jonathan Pereira',
  'José Mariano Sousa',
  'José Leonardo Aguiar',
  'Lucilia Neto',
  'Luis Pereira',
  'Luis Reis',
  'Miguel Lemos',
  'Nuno Gabriel Freitas',
  'Nuno Santos',
  'Pedro João Freitas',
  'Pedro Tiago Freitas',
  'Rafael Abreu',
  'Rafael Fonçalves',
  'Roberto Barreto',
  'Sofia Sousa',
  'Uvis Peleja',
  'Vando Freitas'
].map((value) => ({ value, label: value, name: 'falcoeiros' }));

export const aves = [
  'Dupond',
  'Dilius',
  'Scotch',
  'Leia',
  'Jet',
  'Petra',
  'Lusitano',
  'Lúcifer',
  'Jonny',
  'Pidgy',
  'Zarco',
  'Marley',
  'Thunder',
  'Beca',
  'India',
  'Joe',
  'Jimmy',
  'Duna',
  'Bubu',
  'Honey'
].map((value) => ({ value, label: value, name: 'birds' }));

export const clientes = [
  'Enotel',
  'Pestana Casino Park',
  'Pestana Carlton Madeira',
  'Pestana Promenade',
  'Pestana Grand',
  'The Cliff Bay',
  'Porto Mare',
  'Porto Santa Maria',
  'Meliá',
  'Royal Savoy',
  'Savoy Palace',
  'Saccharum',
  'Next',
  "Belmond Reid's Palace",
  'Forum Madeira',
  "McDonald's - Avenida do Mar",
  'Sodiprave',
  'Rama',
  'Portos da Madeira',
  'Aeroporto da Madeira',
  'Porto de Recreio da Calheta',
  'Câmara Municipal da Calheta',
  'The Yeatman',
  'World of Wine',
  'VILA VITA',
  'Alma Shopping',
  "McDonald's - Porto",
  'Câmara Municipal de Coimbra',
  'Câmara Municipal de Santarém',
  'Hospital de Santarém',
  'JAP',
  'CARVOEIRO CLUBE',
  'Aeroporto do Porto Santo',
  'OPORTO CRICKET AND LAWN TENNIS CLUB',
  'HILTON PORTO GAIA',
  'THE LODGE',
  "McDonald's - Parque das Nações",
  "McDonald's - Belém",
  'Allegro',
  'Galo Resort'
].map((value) => ({ value, label: value, name: 'clients' }));
