export const falcoeiros = [
  'Amilcar Fernandes',
  'Claudio Rodrigues',
  'David Silva',
  'Eduardo Esteves',
  'Filipe Coelho',
  'Flavia Carneiro',
  'Francisco Caramelo',
  'Guilherme',
  'Joana Silva',
  'João Francisco Silva',
  'João Vitor Sousa',
  'Jonathan Pereira',
  'José Mariano Sousa',
  'José Leonardo Aguiar',
  'Lucilia Neto',
  'Luis Pereira',
  'Luis Reis',
  'Miguel Lemos',
  'Nuno Gabriel Freitas',
  'Nuno Santos',
  'Pedro João Freitas',
  'Pedro Tiago Freitas',
  'Rafael Abreu',
  'Rafael Fonçalves',
  'Roberto Barreto',
  'Sofia Sousa',
  'Uvis Peleja',
  'Vando Freitas',
].map((value) => ({ value, label: value }));

export const aves = [
  'Dupond',
  'Dilius',
  'Scotch',
  'Leia',
  'Jet',
  'Petra',
  'Lusitano',
  'Lúcifer',
  'Jonny',
  'Pidgy',
  'Zarco',
  'Marley',
  'Thunder',
  'Beca',
  'India',
  'Joe',
  'Jimmy',
  'Duna',
  'Bubu',
  'Honey',
].map((value) => ({ value, label: value }));

export const clientes = [
  { value: 'Enotel', label: 'Enotel' },
  { value: 'Pestana Casino Park', label: 'Pestana Casino Park' },
  { value: 'Pestana Carlton Madeira', label: 'Pestana Carlton Madeira' },
  { value: 'Pestana Promenade', label: 'Pestana Promenade' },
  { value: 'Pestana Grand', label: 'Pestana Grand' },
  { value: 'The Cliff Bay', label: 'The Cliff Bay' },
  { value: 'Porto Mare', label: 'Porto Mare' },
  { value: 'Porto Santa Maria', label: 'Porto Santa Maria' },
  { value: 'Meliá', label: 'Meliá' },
  { value: 'Royal Savoy', label: 'Royal Savoy' },
  { value: 'Savoy Palace', label: 'Savoy Palace' },
  { value: 'Saccharum', label: 'Saccharum' },
  { value: 'Next', label: 'Next' },
  { value: "Belmond Reid's Palace", label: "Belmond Reid's Palace" },
  {value: 'Forum Madeira', label: 'Forum Madeira'},
  {value: "McDonald's - Avenida do Mar", label: "McDonald's - Avenida do Mar"},
  {value: 'Sodiprave', label: 'Sodiprave'},
  {value: 'Rama', label: 'Rama'},
  {value: 'Portos da Madeira', label: 'Portos da Madeira'},
  {value: 'Aeroporto da Madeira', label: 'Aeroporto da Madeira'},
  {value: 'Porto de Recreio da Calheta', label: 'Porto de Recreio da Calheta'},
  {value: 'Câmara Municipal da Calheta', label: 'Câmara Municipal da Calheta'},
  {value: 'The Yeatman', label: 'The Yeatman'},
  {value: 'World of Wine', label: 'World of Wine'},
  {value: 'VILA VITA', label: 'VILA VITA'},
  {value: 'Alma Shopping', label: 'Alma Shopping'},
  {value: "McDonald's - Porto", label: "McDonald's - Porto"},
  {value: 'Câmara Municipal de Coimbra', label: 'Câmara Municipal de Coimbra'},
  {value: 'Câmara Municipal de Santarém', label: 'Câmara Municipal de Santarém'},
  {value: 'Hospital de Santarém', label: 'Hospital de Santarém'},
  {value: 'JAP', label: 'JAP'},
  {value: 'CARVOEIRO CLUBE', label: 'CARVOEIRO CLUBE'},
  {value: 'Aeroporto do Porto Santo', label: 'Aeroporto do Porto Santo'},
  {value: 'OPORTO CRICKET AND LAWN TENNIS CLUB', label: 'OPORTO CRICKET AND LAWN TENNIS CLUB'},
  {value: 'HILTON PORTO GAIA', label: 'HILTON PORTO GAIA'},
  {value: 'THE LODGE', label: 'THE LODGE'},
  {value: "McDonald's - Parque das Nações", label: "McDonald's - Parque das Nações"},
  {value: "McDonald's - Belém", label: "McDonald's - Belém"},
  {value: 'Allegro', label: 'Allegro'},
  {value: 'Galo Resort', label: 'Galo Resort'},
];
